### PR TITLE
QR-Code (base64) generation added

### PR DESCRIPTION
**Pull request by r4mp**
I dont know, how I can reopen the old request, so...

### CODE REVIEW

**Comment by jklmnn** [comment]
Well, not anymore since github says that this pullrequest is even. Just let's take this.
Why have you used `data:image/gif;base64`? Shouldn't that be `png;base64`?

**Comment by r4mp** [comment]
ehhm.. you're totally right... my fault -.-*

**Comment by jklmnn** [comment]
It works for me, we will fix that after merge.

**Comment by r4mp** [comment]
Let me make a tidy pull request :)

**Pull request closed without merging**
