### PR TITLE
Create db user

### LINKED ISSUE #19: Create Option to Create User/Password/Database
Create in the Install File an Option to Create a User with Password and Database only for ShoppingList

### PR DESCRIPTION
**Pull request by ghost**
The user can now choose if he want to create a new user or take his existing user.
resolve #19 
fixed #19

### CODE REVIEW

**Comment by ghost** [comment]
Please @J-8 merge this.
Thanks

**Comment by J-8** [comment]
Hey, thanks! Awesome. I really appreciate us working together!
I will merge when I get home tonight.

**Comment by J-8** [comment]
I tested it at home and it works perfect.
The only thing I find confusing is that the initial .htaccess should take INSTALL.php as the index file, and after the setup has completed successfully it should be api.php.

I really love it. You are clearly talented with php:)

**Comment by ghost** [comment]
Thanks
I hope i can help you more and more with that

**Comment by J-8** [comment]
It is as much your project now as it is mine ;)
I will add the .htaccess stuff tomorrow and then merge! Thanks again!

**Comment by ghost** [comment]
No I can no develop Android apps that is the next step

**Comment by J-8** [comment]
No good backend, no good app:) 

El 25 de agosto de 2015 20:56:19 CEST, Malte Kiefer notifications@github.com escribió:

> No I can no develop Android apps that is the next step
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/J-8/ShoppingList_backend/pull/21#issuecomment-134701209

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ghost** [comment]
When do you merge this?

**Comment by J-8** [comment]
Could you change that in the beginning .htaccess should take INSTALL.php as the index file, and after the setup has completed successfully it should be api.php?
Sorry, have a lot of stuff to do right now :/

**Comment by ghost** [comment]
No problem. But please merge first, then it is easyer for me to do this.

**Pull request merged**
