### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jinformatique**
correction of installation path and added some info and direct link to the wiki.

### CODE REVIEW

**Comment by jklmnn** [comment]
Thanks for the commit. The install link is supposed to be / because it redirects to api.php which checks if the auth key is set, and if not it redirects to INSTALL.PHP.
We usually said that pull requests should be merged into devel. Unfortunately this project seems to be a bit asleep because of time issues of all devs.
@J-8 what should we do?

**Comment by jinformatique** [comment]
ok sorry but when I opened http://your.path/ I was not redirected to INSTALL.php
I got an Error 403.
I found it would be better to create an index.php it would be less misleading.

I hope the project is not dead, because I found it very cool and useful.
I can do another pull request into devel, and you can ignore this one.

**Comment by J-8** [comment]
Hey. Thanks for your support.
This project is not dead, but I personally have no time for at least the rest of the year due to my bachelor thesis. However, I cannot wait to get back to it ;)

**Comment by ghost** [comment]
Please make a Request to the devel part.
Then I will merge it.
Sorry, the project is not dead. 
I will start with lot of changes next week.
So make a rewuest in devel and I will upated it next week

**Comment by jklmnn** [comment]
@beli3ver He already opened #72

**Pull request closed without merging**
