### PR TITLE
INSTALL.php

### LINKED ISSUE #14: Create install.php
Create install.php for shared hosting support and automatic creation of MySQL database.
Also supplies base for future features.

### PR DESCRIPTION
**Pull request by ghost**
resolve #14

### CODE REVIEW

**Comment by J-8** [comment]
I really like it. Simplicity is key!

A couple of things. What I think is really problematic is that the actual user to create the database is most likely root. Therefore the user in config.php now is also root. That should not happen.

Another field where you can enter the new user should be available. The database should also be created automatically. That user is added to mysql, and granted only rights to the newly created database and table with a random password. The command in the current README has that, except for the random password.

The hashed $authKey is not within ' '.

Thanks!

Would it make sense put to 'unlink(**FILE**);' on success, so that install.php gets deleted automatically?

**Comment by ghost** [comment]
Yeah i will put it in the api.php file.
But here the same problem wrong file rights no unlink.

Ok but on my way I think is easyer for me to create a user as root.
On the other habd shared hoster normaly have only access to one user and can't create more

**Comment by J-8** [comment]
Oh okay, did not know that.
If it is now too much trouble, maybe you could add an option, so the user has the choice.
Thanks again!

**Comment by ghost** [comment]
I will
do will merge this or should I

**Comment by J-8** [comment]
Thanks!
I added quotes to the authKey. In my config.php they were missing.

**Pull request merged**
