### PR TITLE
QR-Code generation added

### PR DESCRIPTION
**Pull request by r4mp**
First step for semi automatic client configuration

### CODE REVIEW

**Comment by ghost** [comment]
Ok @r4mp that's great, I will give you more rights, so that you could work directly with us.
Please read this first:
https://github.com/GroundApps/ShoppingList/wiki
https://github.com/GroundApps/ShoppingList/wiki/Roadmap
https://github.com/GroundApps/ShoppingList_Backend/issues/34

**Comment by jklmnn** [comment]
@r4mp How do I get the qrcodelib?

**Comment by jklmnn** [comment]
Tested it and :+1:

**Comment by r4mp** [comment]
> @r4mp How do I get the qrcodelib?

You can use the submodule command:
git submodule update --init

**Comment by jklmnn** [comment]
I already got it, thanks!
@J-8 will a QR option be available in a soon release? If so I would merge this PR.

**Comment by J-8** [comment]
Sure! Have tested that before and it works flawlessly (If you have the zxing barcode scanner installed).
But how would you solve the problem of generating the qrcode again after the setup has been closed? It exposes url and password, so it cannot be kept. And generating it on the device would mean another library just for that one step which I think is unnecessary. Maybe the api could generate a qrcode when triggered? I could just grab the image and display it.

**Comment by jklmnn** [comment]
@r4mp can you catch the image data before saving it, transforming it into base64 and display this as image? Base64 encoded image data can be displayed by browsers and if we keep it as variable, we don't need to save it on disk so there's no way to get the image otherwise (unless you have RAM access, but then you have bigger problems than just this).

**Comment by r4mp** [comment]
Sure, I will do this tomorrow.

**Comment by jklmnn** [comment]
Can I close this request (I would assume that you would create a new pull request)?

**Comment by J-8** [comment]
No hurries there. Thanks again and welcome! :)

**Comment by J-8** [comment]
I have just seen the option for zxing that with the barcode scanner app we can also generate the barcode and display it. So no need to handle that on the backend.

**Comment by jklmnn** [comment]
Why do you want to create the code on the phone? The generated auth key isn't there. Or do I understand something wrong?

**Comment by J-8** [comment]
I was probably not explaining it clearly:) 
I was thinking about what happens when you want to configure a phone but at the time of the backend installation you do not have it at hand. You could then, whenever you want to configure another phone, generate the qr code on your phone and scan it with the other. Of course only after successfully configuring yours. 
Does that make more sense now?

**Comment by r4mp** [comment]
I understand what you mean. I think for this idea maybe it's better to use the encrypted api key on client side. Otherwise it's not possible to generate the QR code on server side, because after finishing the setup only the encrypted one is stored. 

EDIT: And if you want generate the QR code on the mobile you have the same problem. Unless you store the plain api key on the phone.

**Comment by J-8** [comment]
Now I am confused.
What happens is, install.php takes the user-supplied authkey (not the encrypted one) and generates a qr code from it, also including the host and the bool ssl. Right? This data is then saved in the app via scanning the code. The password is then submitted in cleartext to the api to get the list. The api takes the hash from the submitted key and compares it to the key in config.php.

So with the same data the exact same qr code can be produced in the app and can be used to configure another phone that you did not have during backend installation. 
I hope it makes sense:D

**Comment by jklmnn** [comment]
I think we should concentrate on the server side here. The client side should be another issue, but in the app repo.
On the server side we should not store the plaintext at all even if this means that we can generate the cody only once. But storing it plain will make all other security measurements useless.

**Comment by r4mp** [comment]
Full ACK

**Comment by J-8** [comment]
But if we don't put the cleartext in the qr code, the key would have to be entered manually in the app. Is that the intended behavior?

**Comment by jklmnn** [comment]
The clear text is in the QR code. The point is that the QR code only exists in RAM on the server and is only showed once. We might add an option to save the QR code locally as backup.

**Comment by J-8** [comment]
And I think it is a good thing it is only shown once and never saved. The app does not need a saved version, let me worry about that :)

**Comment by J-8** [comment]
So this could be merged couldn't it?

**Comment by jklmnn** [comment]
Idk, I thought @r4mp will reopen it when he has implemented that the QR code is not saved on disk? Or will that be done later?

**Comment by J-8** [comment]
Okay, then I misunderstood.

**Comment by r4mp** [comment]
Like @jklmnn said, I will fix the implemantation and reopen the request later this day.

**Comment by r4mp** [comment]
Cool, thx!

**Pull request closed without merging**
